[phases.setup]
nixPkgs = ["python311", "bash"]
[phases.install]
cmds = [
    "python3.11 -m venv /opt/venv",
    "source /opt/venv/bin/activate && pip install --upgrade pip",
    "source /opt/venv/bin/activate && pip install PyJWT==2.8.0",
    "source /opt/venv/bin/activate && pip install -r requirements.txt",
    "chmod +x start.sh"
]
[start]
cmd = "source /opt/venv/bin/activate && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
