[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "bash"]
[phases.install]
cmds = [
    "python3.11 -m pip install --upgrade pip",
    "python3.11 -m pip install PyJWT==2.8.0",
    "python3.11 -m pip install -r requirements.txt",
    "chmod +x start.sh"
]
[start]
cmd = "python3.11 -m uvicorn app.main:app --host 0.0.0.0 --port "
