[phases.setup]
nixPkgs = ["python311", "bash"]
[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install PyJWT==2.8.0",
    "pip install -r requirements.txt",
    "chmod +x start.sh"
]
[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port "
